version: "3.9"
services:
#  randomstring:
#    image: randomstring
#    build:
#      dockerfile: ./Dockerfile
#    ports:
#      - "8001:8001"
#    depends_on:
#      - db
#    restart: unless-stopped
  db:
    image: mysql:8.0.31
    ports:
      - "6601:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: unless-stopped
    volumes:
      - db_data_randomstring:/var/lib/mysql
      - ./deployment/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data_randomstring:
    driver: local
