server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://${DOCKER_HOST_IP:localhost}:6601/poollearn
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
